name: run RemoveLogFile.py

on:
  #workflow_dispatch
   schedule:
     - cron: "5 18 * * MON-FRI" # Runs at 11 pm for Monday - Friday to delete log file

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip3 install pytz

      - name: execute py script # run main.py
        run: python RemoveLogFile.py
